import "server-only";
import { sendStatusEmail } from "@/lib/email";
import { createOccurrence, updateOccurrence, softDeleteOccurrence, changeStatus, createComment, updateComment, softDeleteComment, getOccurrence, getCommentAuthorId, getAuthorEmail, uploadPhoto, removePhoto } from "../_data-access/occurrences";
import type { CurrentUser, OccurrenceCategory, OccurrenceStatus } from "@/lib/domain";

function canManage(user: CurrentUser, authorId: string) { return user.role === "staff" || user.id === authorId; }
export async function createOccurrenceService(user: CurrentUser, input: { title: string; description: string; category: OccurrenceCategory; location: string; photo?: File | null }) { if (user.role !== "resident") throw new Error("FORBIDDEN"); const id = await createOccurrence({ ...input, authorId: user.id }); if (input.photo) { try { await uploadPhoto(id, input.photo); } catch (error) { await softDeleteOccurrence(id); throw error; } } return id; }
export async function updateOccurrenceService(user: CurrentUser, input: { id: string; title: string; description: string; category: OccurrenceCategory; location: string; photo?: File | null; removePhoto?: boolean }) { const item = await getOccurrence(input.id); if (!item || !canManage(user, item.authorId)) throw new Error("FORBIDDEN"); await updateOccurrence(input); if (input.removePhoto || input.photo) { await removePhoto(input.id); if (input.photo) await uploadPhoto(input.id, input.photo); } }
export async function deleteOccurrenceService(user: CurrentUser, id: string) { const item = await getOccurrence(id); if (!item || !canManage(user, item.authorId)) throw new Error("FORBIDDEN"); await removePhoto(id); await softDeleteOccurrence(id); }
export async function addCommentService(user: CurrentUser, input: { occurrenceId: string; content: string }) { const item = await getOccurrence(input.occurrenceId); if (!item) throw new Error("NOT_FOUND"); await createComment({ ...input, authorId: user.id }); }
export async function editCommentService(user: CurrentUser, input: { id: string; content: string }) { if (user.role !== "staff" && (await getCommentAuthorId(input.id)) !== user.id) throw new Error("FORBIDDEN"); await updateComment(input); }
export async function deleteCommentService(user: CurrentUser, id: string) { if (user.role !== "staff" && (await getCommentAuthorId(id)) !== user.id) throw new Error("FORBIDDEN"); await softDeleteComment(id); }
export async function changeStatusService(user: CurrentUser, id: string, status: OccurrenceStatus) { const item = await getOccurrence(id); if (!item || !canManage(user, item.authorId)) throw new Error("FORBIDDEN"); const changed = await changeStatus(id, status); if (!changed) return { changed: false, notificationSent: false }; let notificationSent = false; const email = await getAuthorEmail(item.authorId); if (email) { try { await sendStatusEmail(email, item.title, status); notificationSent = true; } catch (error) { console.error("Status notification failed", { occurrenceId: id, error }); } } return { changed: true, notificationSent }; }
