import "server-only";
import { createClient } from "@/lib/supabase/server";
import type { OccurrenceCategory, OccurrenceStatus } from "@/lib/domain";

const fields = "id,title,description,category,location,status,author_id,status_changed_at,created_at,updated_at,occurrence_photos(storage_path)";
function mapRow(row: any) { const author = Array.isArray(row.profiles) ? row.profiles[0] : row.profiles; const photo = Array.isArray(row.occurrence_photos) ? row.occurrence_photos[0] : row.occurrence_photos; return { id: row.id, title: row.title, description: row.description, category: row.category, location: row.location, status: row.status, authorId: row.author_id, authorName: author?.display_name ?? "Morador", photoPath: photo?.storage_path ?? null, photoUrl: null as string | null, createdAt: row.created_at, updatedAt: row.updated_at, statusChangedAt: row.status_changed_at }; }
export async function listOccurrences(filters: { status?: OccurrenceStatus; category?: OccurrenceCategory; page?: number }) { const supabase = await createClient(); let query = supabase.from("occurrences").select(`${fields},profiles!occurrences_author_id_fkey(display_name)`, { count: "exact" }).is("deleted_at", null).order("created_at", { ascending: false }).range(((filters.page ?? 1) - 1) * 10, (filters.page ?? 1) * 10 - 1); if (filters.status) query = query.eq("status", filters.status); if (filters.category) query = query.eq("category", filters.category); const { data, count, error } = await query; if (error) throw error; return { items: (data ?? []).map(mapRow), total: count ?? 0 }; }
export async function getOccurrence(id: string) { const supabase = await createClient(); const { data, error } = await supabase.from("occurrences").select(`${fields},profiles!occurrences_author_id_fkey(display_name)`).eq("id", id).is("deleted_at", null).maybeSingle(); if (error) throw error; if (!data) return null; const item = mapRow(data); if (item.photoPath) { const signed = await supabase.storage.from("occurrence-photos").createSignedUrl(item.photoPath, 3600); item.photoUrl = signed.data?.signedUrl ?? null; } return item; }
export async function createOccurrence(input: { authorId: string; title: string; description: string; category: OccurrenceCategory; location: string }) { const supabase = await createClient(); const { data, error } = await supabase.from("occurrences").insert({ author_id: input.authorId, title: input.title, description: input.description, category: input.category, location: input.location, status: "open" }).select("id").single(); if (error) throw error; return data.id as string; }
export async function updateOccurrence(input: { id: string; title: string; description: string; category: OccurrenceCategory; location: string }) { const supabase = await createClient(); const { error } = await supabase.from("occurrences").update({ title: input.title, description: input.description, category: input.category, location: input.location }).eq("id", input.id).is("deleted_at", null); if (error) throw error; }
export async function softDeleteOccurrence(id: string) { const supabase = await createClient(); const { error } = await supabase.from("occurrences").update({ deleted_at: new Date().toISOString() }).eq("id", id).is("deleted_at", null); if (error) throw error; }
export async function changeStatus(id: string, status: OccurrenceStatus) { const supabase = await createClient(); const { data, error } = await supabase.from("occurrences").update({ status, status_changed_at: new Date().toISOString() }).eq("id", id).neq("status", status).is("deleted_at", null).select("id,author_id,title,status").maybeSingle(); if (error) throw error; return data; }
export async function listComments(occurrenceId: string) { const supabase = await createClient(); const { data, error } = await supabase.from("comments").select("id,occurrence_id,author_id,content,created_at,updated_at,profiles!comments_author_id_fkey(display_name)").eq("occurrence_id", occurrenceId).is("deleted_at", null).order("created_at", { ascending: true }); if (error) throw error; return (data ?? []).map((row: any) => ({ id: row.id, occurrenceId: row.occurrence_id, authorId: row.author_id, authorName: row.profiles?.display_name ?? "Usuário", content: row.content, createdAt: row.created_at, updatedAt: row.updated_at })); }
export async function createComment(input: { occurrenceId: string; authorId: string; content: string }) { const supabase = await createClient(); const { error } = await supabase.from("comments").insert({ occurrence_id: input.occurrenceId, author_id: input.authorId, content: input.content }); if (error) throw error; }
export async function updateComment(input: { id: string; content: string }) { const supabase = await createClient(); const { error } = await supabase.from("comments").update({ content: input.content }).eq("id", input.id).is("deleted_at", null); if (error) throw error; }
export async function softDeleteComment(id: string) { const supabase = await createClient(); const { error } = await supabase.from("comments").update({ deleted_at: new Date().toISOString() }).eq("id", id).is("deleted_at", null); if (error) throw error; }
export async function getCommentAuthorId(id: string) { const supabase = await createClient(); const { data, error } = await supabase.from("comments").select("author_id").eq("id", id).maybeSingle(); if (error) throw error; return data?.author_id ?? null; }
export async function getAuthorEmail(profileId: string) { const supabase = await createClient(); const { data, error } = await supabase.from("profile_contacts").select("email").eq("profile_id", profileId).maybeSingle(); if (error) throw error; return data?.email ?? null; }
export async function uploadPhoto(occurrenceId: string, file: File) { const supabase = await createClient(); const extension = file.type === "image/png" ? "png" : "jpg"; const path = `occurrences/${occurrenceId}/${crypto.randomUUID()}.${extension}`; const { error: uploadError } = await supabase.storage.from("occurrence-photos").upload(path, file, { contentType: file.type, upsert: false }); if (uploadError) throw uploadError; const { error: rowError } = await supabase.from("occurrence_photos").insert({ occurrence_id: occurrenceId, storage_path: path, mime_type: file.type, size_bytes: file.size }); if (rowError) { await supabase.storage.from("occurrence-photos").remove([path]); throw rowError; } return path; }
export async function removePhoto(occurrenceId: string) { const supabase = await createClient(); const { data } = await supabase.from("occurrence_photos").select("storage_path").eq("occurrence_id", occurrenceId).maybeSingle(); if (data?.storage_path) await supabase.storage.from("occurrence-photos").remove([data.storage_path]); await supabase.from("occurrence_photos").delete().eq("occurrence_id", occurrenceId); }
