"use server";
import { revalidatePath } from "next/cache";
import type { ActionResult } from "@/lib/domain";
import { requireUser } from "@/lib/auth";
import { occurrenceSchema, occurrenceUpdateSchema, statusSchema, commentSchema, commentUpdateSchema } from "@/lib/validations";
import { addCommentService, changeStatusService, createOccurrenceService, deleteCommentService, deleteOccurrenceService, editCommentService, updateOccurrenceService } from "@/features/occurrences/_services/occurrence-service";
export async function createOccurrenceAction(_: unknown, formData: FormData): Promise<ActionResult<{ id: string }>> { const user = await requireUser("resident"); const parsed = occurrenceSchema.safeParse(Object.fromEntries(formData)); const photo = formData.get("photo"); if (!parsed.success) return { success: false, message: "Revise o formulário.", fieldErrors: parsed.error.flatten().fieldErrors }; if (photo instanceof File && photo.size > 0 && (!(["image/jpeg", "image/png"].includes(photo.type)) || photo.size > 5 * 1024 * 1024)) return { success: false, message: "A foto deve ser JPG ou PNG e ter no máximo 5 MB." }; try { const id = await createOccurrenceService(user, { ...parsed.data, photo: photo instanceof File && photo.size > 0 ? photo : null }); revalidatePath("/morador/ocorrencias"); return { success: true, data: { id }, message: "Ocorrência criada com sucesso." }; } catch { return { success: false, message: "Não foi possível criar a ocorrência." }; } }
export async function updateOccurrenceAction(_: unknown, formData: FormData): Promise<ActionResult> { const user = await requireUser(); const parsed = occurrenceUpdateSchema.safeParse(Object.fromEntries(formData)); const photo = formData.get("photo"); if (!parsed.success) return { success: false, message: "Revise o formulário.", fieldErrors: parsed.error.flatten().fieldErrors }; if (photo instanceof File && photo.size > 0 && (!(["image/jpeg", "image/png"].includes(photo.type)) || photo.size > 5 * 1024 * 1024)) return { success: false, message: "A foto deve ser JPG ou PNG e ter no máximo 5 MB." }; try { await updateOccurrenceService(user, { ...parsed.data, photo: photo instanceof File && photo.size > 0 ? photo : null, removePhoto: formData.get("removePhoto") === "on" }); revalidatePath("/morador/ocorrencias"); revalidatePath(`/morador/ocorrencias/${parsed.data.id}`); return { success: true, message: "Ocorrência atualizada." }; } catch { return { success: false, message: "Não foi possível atualizar a ocorrência." }; } }
export async function deleteOccurrenceAction(id: string): Promise<ActionResult> { const user = await requireUser(); try { await deleteOccurrenceService(user, id); revalidatePath("/morador/ocorrencias"); return { success: true, message: "Ocorrência excluída." }; } catch { return { success: false, message: "Não foi possível excluir a ocorrência." }; } }
export async function changeStatusAction(_: unknown, formData: FormData): Promise<ActionResult<{ notificationSent: boolean }>> { const user = await requireUser(); const parsed = statusSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { success: false, message: "Status inválido." }; try { const result = await changeStatusService(user, parsed.data.id, parsed.data.status); revalidatePath("/morador/ocorrencias"); revalidatePath(`/morador/ocorrencias/${parsed.data.id}`); return { success: true, data: { notificationSent: result.notificationSent }, message: result.changed ? "Status atualizado." : "O status já estava selecionado.", warning: result.changed && !result.notificationSent ? "Status atualizado, mas não foi possível enviar a notificação." : undefined }; } catch { return { success: false, message: "Não foi possível alterar o status." }; } }
export async function createCommentAction(_: unknown, formData: FormData): Promise<ActionResult> { const user = await requireUser(); const parsed = commentSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { success: false, message: "Escreva um comentário válido.", fieldErrors: parsed.error.flatten().fieldErrors }; try { await addCommentService(user, parsed.data); revalidatePath(`/morador/ocorrencias/${parsed.data.occurrenceId}`); return { success: true, message: "Comentário publicado." }; } catch { return { success: false, message: "Não foi possível publicar o comentário." }; } }
export async function updateCommentAction(_: unknown, formData: FormData): Promise<ActionResult> { const user = await requireUser(); const parsed = commentUpdateSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { success: false, message: "Comentário inválido." }; try { await editCommentService(user, parsed.data); return { success: true, message: "Comentário atualizado." }; } catch { return { success: false, message: "Não foi possível atualizar o comentário." }; } }
export async function deleteCommentAction(id: string, occurrenceId: string): Promise<ActionResult> { const user = await requireUser(); try { await deleteCommentService(user, id); revalidatePath(`/morador/ocorrencias/${occurrenceId}`); return { success: true, message: "Comentário excluído." }; } catch { return { success: false, message: "Não foi possível excluir o comentário." }; } }
